server.servlet.context-path: /
spring.view.prefix: /WEB-INF/views/
spring.view.suffix: .jsp
spring.view.view-names: pluginfree/**

spring.thymeleaf.view-names: /*
spring.thymeleaf.prefix: classpath:templates/
spring.thymeleaf.suffix: .html

